### ISSUE TITLE
Adapt the Pages public flow diagram for customers to reference

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/cg-diagrams#156]
Modify and adapt the current Pages public flow diagram for customers to leverage for their own documentation and use.

## Acceptance Criteria

- [ ] Creates a new customer focuses public flow diagram
- [ ] Adapts the diagram language to be more customer centric
- [ ] Create SVG and PNG outputs

**Comment by KKAtila** [comment]
@apburnes 
Can we add the following to the diagram?
- Authenticator for the Site Admin
- Webhook for site to start the build or updates/refresh
Thank you
